name: "[PR] Vulnerability Scanning"
on:
  pull_request:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    # Permissions key is required for CodeQL SARIF Upload, per the docs:
    # https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      
      - name: Docker Image Build for security scan - Alpine
        uses: docker/build-push-action@v6
        with:
          push: false
          target: alpine
          tags: app:alpine
          file: Dockerfile
          build-args: "GOARCH=amd64"

      - name: Docker Image Build for security scan - Scratch
        uses: docker/build-push-action@v6
        with:
          push: false
          target: scratch-release
          tags: app:scratch
          file: Dockerfile
          build-args: "GOARCH=amd64"
      
      - uses: anchore/scan-action@v6
        id: scan-alpine
        with:
          image: "app:alpine"
          severity-cutoff: "low"
          by-cve: true
          fail-build: false

      - uses: anchore/scan-action@v6
        id: scan-scratch
        with:
          image: "app:scratch"
          severity-cutoff: "low"
          by-cve: true
          fail-build: false
      
      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan-alpine.outputs.sarif }}
          category: alpine-vulnerability-scan
      
      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan-scratch.outputs.sarif }}
          category: scratch-vulnerability-scan
